START TRANSACTION ;

SELECT * FROM guestbooks;

UPDATE guestbooks
SET title = 'Diubah Oleh User 1'
WHERE id = 9;

COMMIT;

-- LOCKING MANUAL

START TRANSACTION ;

SELECT * FROm products;

-- TAMBAHKAN FOR BLABLA UNTUK LOCK
SELECT * FROM products WHERE id = 'P0001' FOR UPDATE;

UPDATE products
SET quantity = quantity - 10
WHERE id = 'P0001';

COMMIT ;

#  DEADLOCK

START TRANSACTION ;

SELECT * FROM products WHERE id = 'P0001' FOR UPDATE ;

SELECT * FROM products WHERE id = 'P0002' FOR UPDATE ;

# LOCK TABLE READ
-- USER 1 HANYA BISA READ TAPI TIDAK BISA WRITE
-- USER 2 HANYA BISA READ SAJA

LOCK TABLES products READ;

UPDATE products
SET quantity = 100
WHERE id = 'P0001';

UNLOCK TABLES ;

# LOCK TABLE WRITE
-- USER 1 BISA MELAKUKAN READ DAN WRITE 
-- USER 2 HANYA BISA MELAKUKAN READ SAJA
LOCK TABLES products WRITE ;

UPDATE products
SET quantity = 100
WHERE id = 'P0001';

SELECT * FROM products;

UNLOCK TABLES ;

# LOCK INSTANCE
-- DALAM KONDISI INI MAKA SEMUA PERINTAH SQL ATAU LEBIH TEPATNYA DDL PADA DATABASE AKAN DIBLOCK DAN TIDAK BISA DIJALANKAN SAMPAI DI UNLOCK
-- BIASANYA LOCK INSTANCE DIGUNAKNA KETIKA MELAKUKAN UPDATE

LOCK INSTANCE FOR BACKUP;

UNLOCK INSTANCE;










